### ISSUE TITLE
Need to install unrar as well in Bazarr

### ISSUE THREAD

**Issue by D3SL** [vzamora/Proxmox-Cheatsheet#5]
What the issue says on the tin. Aside from having to run apt update/upgrade and then the main install string a second time I also had to install unrar manually as bazarr kicked a `BinaryNotFound` error on startup without it.

**Comment by vzamora** [comment]
In the first line, unrar-free and unzip are both installed.  What CT template did you use?  I used a Debian11 CT just now and installed it successfully with no error flags.

Can you give me some more information on what you did?  Did you copy/paste the top line into the shell?
